backend:
  name: github
  repo: hackshuu/hackshuu.github.io # Seu repositório no GitHub
  branch: main
  base_url: https://decap-oauth-gateway.sektual.com # Gateway OAuth gratuito para GitHub Pages
  auth_endpoint: /auth

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Postagens & Vídeos"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "ID do Vídeo no YouTube", name: "youtube_id", widget: "string", required: false }
      - { label: "Conteúdo do Post", name: "body", widget: "markdown" }
