backend:
  name: git-gateway
  repo: hackshuu/hackshuu.github.io
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/33a7e2fa-0bde-4773-9067-a5685a5106bc/pkce
  auth_token_endpoint: /sites/33a7e2fa-0bde-4773-9067-a5685a5106bc/token
  gateway_url: https://gateway.decapbridge.com

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

site_url: https://hackshuu.github.io
display_url: https://hackshuu.github.io

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Postagens & Vídeos"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "ID do Vídeo no YouTube", name: "youtube_id", widget: "string", required: false }
      - { label: "Conteúdo do Post", name: "body", widget: "markdown" }
